#!/bin/bash

while(true)
do

    MAVEN_OPTS="-Xmx768m -da -dsa"  mvn exec:java --quiet     -Dexec.args="'$1'"      -Dexec.mainClass="spimedb.Main"

    if [ $? != 2 ]
        then
            break
    fi

    sleep 1

done
